In [1]:
! pip install numpy

You should consider upgrading via the 'C:\Users\Артём\Desktop\Новая папка\python.exe -m pip install --upgrade pip' command.


In [8]:
import numpy as np

a = np.array([1, 2, 3])

b = np.array([-1, -2, -3]).astype(np.float64)

b[1] = '12345'
print(b[1])
print(b.dtype)

e = np.identity(1)
print(e)




12345.0
float64
[[1.]]


In [9]:
import numpy as np


matrix = np.array([[1, 2], [6, 3]])
print(matrix)

[[1 2]
 [6 3]]


In [17]:
import numpy as np

m1 = np.array([[2, 3], [6, 3]])
print(m1.shape)
print(m1)

m2 = np.array([1, 2, 3, 4]).reshape((2, 2))


print(m1 * m2)

print(m1 @ m2)

m3 = m1 @ m2

print(m3)

(2, 2)
[[2 3]
 [6 3]]
[[ 2  6]
 [18 12]]
[[11 16]
 [15 24]]
[[11 16]
 [15 24]]


In [18]:
import numpy as np

m1 = np.array([[2, 3], [6, 3]])

m2 = np.array([1, 2, 3, 4]).reshape((2, 2))


print(m1 * m2)

print(np.linalg.inv(m1))


print(f'result: {np.array([2, 4, 6, 8]).cumsum()}')

[[ 2  6]
 [18 12]]
[[-0.25        0.25      ]
 [ 0.5        -0.16666667]]
result: [ 2  6 12 20]


In [23]:
import numpy as np


n = np.arange(9).reshape((3, 3))
print(n)

print(n[1, :])



[[0 1 2]
 [3 4 5]
 [6 7 8]]
[3 4 5]


In [26]:
import numpy as np


n = np.arange(9).reshape((3, 3))
print(n)
print(n.T)

b = n[:, :]
print(b.ravel())




[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
[0 1 2 3 4 5 6 7 8]


In [29]:
import numpy as np

ones = np.ones(10)
zeros = np.zeros(10)

print(f'ones: {ones}')
print(f'zeros: {zeros}')


print(np.hstack((ones, zeros)))
print(np.vstack((ones, zeros)))


ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [42]:
import numpy as np

n = np.arange(16).reshape((4, 4))

print(n)
print(n.diagonal(-1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 4  9 14]
